# Generated by Django 4.0.4 on 2022-05-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0003_alter_game_rating_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='raterprojectapi.game'),
        ),
        migrations.AlterField(
            model_name='game_review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='raterprojectapi.game'),
        ),
    ]
